# Generated by Django 4.0.1 on 2022-01-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Email', models.EmailField(max_length=500)),
                ('Phone', models.CharField(max_length=500)),
                ('Username', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
            ],
        ),
    ]
